site_name: OHua's Blog
site_url: https://ohua.github.io/Blog
site_description: 一個活在悲慘世界的樂觀青年
site_author: OHua
repo_url: https://github.com/OHua/Blog
pages:
  - Home: index.md
  - About:
      - LICENSE.md
      - README.md
  - Content:
      - 使我感到詭異的Comprehension in Python.md
      - 資料科學家第一週.md
      - 資料科學家第二週.md
      - 資料科學家第三週.md
      - 資料科學家第四週.md
      - 成為Python數據分析達人的第一堂課.md

#theme: readthedocs
#theme_dir: custom_theme

extra_css:
    - css/extra.css
#extra_javascript: [extra.js]

markdown_extensions:
    - toc:
        permalink: 
    - admonition:

copyright: Copyright &copy; 2016 <a href="https://github.com/OHua">OHua</a>. All rights reserved.
#google_analytics: ['UA-27795084-5', 'mkdocs.org']
