site_name: OHua's Blogger
pages:
  - Home: index.md
  - About:
      - about.md
  - tset.md
  - README.md
#theme: readthedocs
#extra_css: [extra.css]
#extra_javascript: [extra.js]
#theme_dir: custom_theme
