site_name: OHua's Blogger
pages:
  - Home: index.md
  - About:
      - about.md
  # - Home:
  #     - 'Section levl 2' :
  #         - 'About' : 'about.md'
  #         - 'Test' : 'test.md'
  - Test: test.md
#theme: readthedocs
#extra_css: [extra.css]
#extra_javascript: [extra.js]
#theme_dir: custom_theme
